### PR TITLE
Migrate to sbt ci release

### LINKED ISSUE #13: Should `bintray` plugin be replaced?
https://github.com/sbt/sbt-autoplugin.g8/blob/master/src/main/g8/project/plugins.sbt#L2

### PR DESCRIPTION
**Pull request by softinio**
This resolves #13 

# Summary

- upgrade SBT and other dependencies
- migrate from `sbt-bintray` to `sbt-ci-release`

# Testing

- Ran `sbt new softinio/sbt-autoplugin.g8 --branch migrate-to-sbt-ci-release`
- Result: https://github.com/softinio/sbt-softinio-test-plugin

Note: Will remove result repo once this PR is merged.

- Terminal Screenshot when running `sbt new` FYI:

image

### CODE REVIEW

**Comment by jastice** [comment]
Thanks! Looks like the CI also needs to be updated or migrated

**Comment by softinio** [comment]
@jastice you read my mind! I was about to say migrating the repos CI probably should be another PR. Saw you did it and have rebased this branch with it. Apparently as my first contribution here you need to approve the workflow.

The travis build file in the generated project doesn't seem to have a publish stage to update to me hence I left it as is. I do think there is value in replacing that with GitHub Actions of course. Perhaps tackle that as a follow up PR?

**Comment by softinio** [comment]
@jastice I went ahead and replaced travis with GitHub actions to the template for the generated project. I  updated my sample project that I mentioned in the description with the new template with this as part of it.

**Comment by jastice** [comment]
Thank you for this!

**Comment by softinio** [comment]
@jastice Thanks

**Pull request merged**
