### PR TITLE
Bump sbt version to 1.2.0

### PR DESCRIPTION
**Pull request by regadas**

### CODE REVIEW

**Review by xuwei-k — CHANGES_REQUESTED** [review]
https://github.com/sbt/sbt/issues/4299

**Comment by jastice** [comment]
thanks!

**Comment by jastice** [comment]
Oops, gonna revert this for the time being.

**Comment by regadas** [comment]
yeah saw the comment from @eed3si9n 👍

**Comment by jastice** [comment]
reapplied it with 1.2.1: https://github.com/sbt/sbt-autoplugin.g8/commit/718b560288adb3eea14812f8e57786c8513cc62f

**Pull request merged**
